# -*- coding: utf-8 -*-
"""RID214533_Desafio04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_aQI99SIt287vMHy2lidbzEFYGKmEyn

# Etapa 1: Análise Descritiva
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("MKT.csv")

print(df.head())
print(df.info())
print(df.describe())

"""# Etapa 2: Análise Exploratória"""

correlation_matrix = df.corr()
sns.heatmap(correlation_matrix, annot=True)
plt.show()

"""# Etapa 3: Modelagem"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X = df[['youtube', 'facebook', 'newspaper']]
y = df['sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression().fit(X_train, y_train)
print(f"Coeficientes: {model.coef_}")
print(f"Intercepto: {model.intercept_}")

"""# Etapa 4: Calculando a Predição"""

from sklearn.metrics import r2_score

y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print(f"R²: {r2}")

new_investment = pd.DataFrame([[1000, 500, 200]], columns=['youtube', 'facebook', 'newspaper'])
predicted_sales = model.predict(new_investment)
print(f"Vendas previstas: {predicted_sales[0]}")